// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ReporterAssist
{
	public partial class WorkView2 : NSView
	{
		public WorkView2 (IntPtr handle) : base (handle)
		{
		}
	}
}
