// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Mac
{
	public partial class NovaTarefaMenu : NSViewController
	{
		public NovaTarefaMenu (IntPtr handle) : base (handle)
		{
		}
	}
}
